import { getAdminOrders, updateOrderStatus } from './admin-service.js';
import { getCurrentLanguage } from './i18n.js';

const labels={ar:{pending:'قيد الانتظار',confirmed:'مؤكد',shipped:'تم الشحن',completed:'مكتمل',cancelled:'ملغى',loading:'جاري تحميل لوحة الإدارة…',denied:'الوصول إلى لوحة الإدارة غير متاح.',title:'إدارة الطلبات',count:'طلب',customer:'العميل',phone:'الهاتف',address:'العنوان',total:'الإجمالي',state:'حالة الطلب',none:'لا توجد طلبات حتى الآن.',fail:'تعذر تحديث حالة الطلب.',saved:'تم تحديث حالة الطلب.',saving:'جارٍ الحفظ…'},fr:{pending:'En attente',confirmed:'Confirmée',shipped:'Expédiée',completed:'Terminée',cancelled:'Annulée',loading:'Chargement de l’administration…',denied:'Accès à l’administration indisponible.',title:'Gestion des commandes',count:'commande',customer:'Client',phone:'Téléphone',address:'Adresse',total:'Total',state:'Statut de la commande',none:'Aucune commande pour le moment.',fail:'Impossible de mettre à jour le statut.',saved:'Statut mis à jour.',saving:'Enregistrement…'},en:{pending:'Pending',confirmed:'Confirmed',shipped:'Shipped',completed:'Completed',cancelled:'Cancelled',loading:'Loading admin…',denied:'Admin access is unavailable.',title:'Order management',count:'order',customer:'Customer',phone:'Phone',address:'Address',total:'Total',state:'Order status',none:'No orders yet.',fail:'Could not update order status.',saved:'Order status updated.',saving:'Saving…'}};
const L=()=>labels[getCurrentLanguage()]||labels.ar;

export async function renderAdminPanel(container){
  if(!container)return; const l=L(); container.innerHTML=`<p>${l.loading}</p>`;
  const result=await getAdminOrders();
  if(!result.ok){container.innerHTML=`<div class="msg">${l.denied}</div>`;return;}
  const locale=getCurrentLanguage()==='ar'?'ar-DZ':getCurrentLanguage()==='fr'?'fr-FR':'en-US';
  const statuses=['pending','confirmed','shipped','completed','cancelled'];
  container.innerHTML=`<div class="admin-head"><div><small>Soukis Admin</small><h2>${l.title}</h2></div><span class="pill">${result.orders.length} ${l.count}</span></div>${result.orders.length?result.orders.map(order=>`<article class="msg admin-order" data-order-id="${escapeHtml(order.id)}"><strong>${getCurrentLanguage()==='ar'?'طلب':getCurrentLanguage()==='fr'?'Commande':'Order'} #${escapeHtml(order.id)}</strong><div>${l.customer}: ${escapeHtml(order.shipping_name||'—')}</div><div>${l.phone}: ${escapeHtml(order.shipping_phone||'—')}</div><div>${l.address}: ${escapeHtml(order.shipping_address||'—')}</div><div>${l.total}: ${Number(order.total||0).toLocaleString(locale)} ${escapeHtml(order.currency||'USD')}</div><select class="admin-status" aria-label="${l.state}">${statuses.map(value=>`<option value="${value}" ${value===order.status?'selected':''}>${l[value]}</option>`).join('')}</select><span class="admin-status-feedback" role="status" aria-live="polite"></span></article>`).join(''):`<div class="msg">${l.none}</div>`}`;
  container.querySelectorAll('.admin-status').forEach(select=>{select.addEventListener('change',async()=>{const card=select.closest('.admin-order');const orderId=card?.dataset.orderId;const feedback=card?.querySelector('.admin-status-feedback');const previous=select.dataset.previous||select.value;if(!orderId)return;select.disabled=true;if(feedback){feedback.textContent=l.saving;feedback.className='admin-status-feedback is-saving';}const updated=await updateOrderStatus(orderId,select.value);select.disabled=false;if(!updated.ok){select.value=previous;if(feedback){feedback.textContent=l.fail;feedback.className='admin-status-feedback is-error';}}else{select.dataset.previous=select.value;if(feedback){feedback.textContent=l.saved;feedback.className='admin-status-feedback is-success';setTimeout(()=>{if(feedback.textContent===l.saved)feedback.textContent='';},2500);}}});select.dataset.previous=select.value;});
}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
