import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { addToCart, getCart, updateCartItem, removeCartItem } from './cart-ui.js';
import { openCheckout } from './order-checkout.js';
import { SOUKIS_CONFIG } from './app-config.js';
import { t, getCurrentLanguage } from './i18n.js';

const supabase = createClient(SOUKIS_CONFIG.supabaseUrl, SOUKIS_CONFIG.supabasePublishableKey);

export function installCartBridge() {
  if (document.documentElement.dataset.soukisCartBridgeInstalled === 'true') return;
  document.documentElement.dataset.soukisCartBridgeInstalled = 'true';
  const modal=()=>document.querySelector('#modal'); const body=()=>document.querySelector('#modalBody');
  const openModal=html=>{if(!modal()||!body())return;body().innerHTML=html;modal().hidden=false;};
  const closeModal=()=>{if(modal())modal().hidden=true;};
  const lang=()=>getCurrentLanguage();
  const text=(ar,fr,en)=>lang()==='ar'?ar:lang()==='fr'?fr:en;
  const locale=()=>lang()==='ar'?'ar-DZ':lang()==='fr'?'fr-FR':'en-US';
  const refreshCartCount=async()=>{const c=document.querySelector('#cartCount');if(!c)return;const cart=await getCart();c.textContent=String(cart.ok?cart.items.reduce((s,i)=>s+Number(i.quantity||0),0):0);};
  const refreshAuthUI=async()=>{const {data:{user}}=await supabase.auth.getUser();const session=document.querySelector('#session');const button=document.querySelector('#authBtn');if(session){session.dataset.loggedIn=user?'true':'';session.textContent=user?text('حسابي','Mon compte','My account'):t('notLogged');}if(button)button.textContent=user?text('تسجيل الخروج','Se déconnecter','Sign out'):t('login');};
  const openAuthModal=()=>{openModal(`<h2>${t('login')}</h2><form id="authForm" class="form"><input name="email" type="email" required autocomplete="email" placeholder="${text('البريد الإلكتروني','Adresse e-mail','Email address')}"><input name="password" type="password" required minlength="6" autocomplete="current-password" placeholder="${text('كلمة المرور','Mot de passe','Password')}"><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="blue" type="submit" data-mode="signin">${text('دخول','Connexion','Sign in')}</button><button type="button" data-mode="signup">${text('إنشاء حساب','Créer un compte','Create account')}</button></div><p id="authMessage" class="msg" hidden></p></form>`);const form=document.querySelector('#authForm'),message=document.querySelector('#authMessage');form?.addEventListener('click',async e=>{const mode=e.target.closest('[data-mode]')?.dataset.mode;if(!mode)return;e.preventDefault();const values=Object.fromEntries(new FormData(form));form.querySelectorAll('button').forEach(b=>b.disabled=true);const result=mode==='signin'?await supabase.auth.signInWithPassword({email:values.email,password:values.password}):await supabase.auth.signUp({email:values.email,password:values.password});form.querySelectorAll('button').forEach(b=>b.disabled=false);message.hidden=false;if(result.error){message.textContent=result.error.message||text('تعذر إتمام العملية.','Opération impossible.','Unable to complete the operation.');return;}if(mode==='signup'&&!result.data.session){message.textContent=text('تم إنشاء الحساب. تحقق من بريدك الإلكتروني ثم سجّل الدخول.','Compte créé. Vérifiez votre e-mail puis connectez-vous.','Account created. Check your email, then sign in.');return;}await refreshAuthUI();await refreshCartCount();message.textContent=text('تم تسجيل الدخول بنجاح.','Connexion réussie.','Signed in successfully.');setTimeout(closeModal,500);});};
  const renderCart=async()=>{const cart=await getCart();if(!cart.ok){openModal(`<h2>${t('cart')}</h2><p class="msg">${text('سجّل الدخول أولًا لعرض سلتك.','Connectez-vous pour voir votre panier.','Sign in to view your cart.')}</p><button class="blue" id="cartLogin">${t('login')}</button>`);document.querySelector('#cartLogin')?.addEventListener('click',()=>{closeModal();openAuthModal();});return;}const items=cart.items||[];if(!items.length){openModal(`<h2>${text('سلة التسوق','Panier','Shopping cart')}</h2><p class="msg">${text('السلة فارغة حاليًا.','Votre panier est vide.','Your cart is empty.')}</p>`);await refreshCartCount();return;}const total=items.reduce((s,i)=>s+Number(i.listings?.price||0)*Number(i.quantity||0),0);const currency=items[0]?.listings?.currency||'DA';openModal(`<h2>${text('سلة التسوق','Panier','Shopping cart')}</h2><div style="display:grid;gap:10px;margin:16px 0">${items.map(i=>{const price=Number(i.listings?.price||0),qty=Number(i.quantity||0),cur=esc(i.listings?.currency||'DA');return `<div style="display:grid;grid-template-columns:1fr auto;gap:12px;padding:14px;border:1px solid #e5e7eb;border-radius:14px"><div><strong>${esc(i.listings?.title||text('منتج','Produit','Product'))}</strong><small style="display:block;color:#6b7280">${price.toLocaleString(locale())} ${cur}</small><div style="display:flex;align-items:center;gap:7px;margin-top:9px"><button type="button" class="cart-qty" data-cart-dec="${esc(i.id)}" aria-label="${text('إنقاص الكمية','Diminuer la quantité','Decrease quantity')}">−</button><b>${qty}</b><button type="button" class="cart-qty" data-cart-inc="${esc(i.id)}" aria-label="${text('زيادة الكمية','Augmenter la quantité','Increase quantity')}">+</button><button type="button" data-cart-remove="${esc(i.id)}" style="margin-inline-start:8px;background:#fee2e2;color:#991b1b">${text('حذف','Supprimer','Remove')}</button></div></div><b>${(price*qty).toLocaleString(locale())} ${cur}</b></div>`;}).join('')}</div><div style="display:flex;justify-content:space-between;align-items:center;gap:10px;margin-top:16px"><h3>${text('الإجمالي','Total','Total')}: ${total.toLocaleString(locale())} ${esc(currency)}</h3><button class="blue" id="checkoutBtn">${text('إتمام الطلب','Commander','Checkout')}</button></div>`);};
  document.addEventListener('click',async e=>{
    const authButton=e.target.closest('#authBtn');if(authButton){e.preventDefault();const {data:{user}}=await supabase.auth.getUser();if(user)await supabase.auth.signOut();else openAuthModal();await refreshAuthUI();await refreshCartCount();return;}
    if(e.target.closest('#cartBtn')){e.preventDefault();await renderCart();return;}
    const inc=e.target.closest('[data-cart-inc]');if(inc){e.preventDefault();const cart=await getCart();const item=cart.items.find(i=>String(i.id)===String(inc.dataset.cartInc));if(item){await updateCartItem(item.id,Number(item.quantity)+1);await refreshCartCount();await renderCart();}return;}
    const dec=e.target.closest('[data-cart-dec]');if(dec){e.preventDefault();const cart=await getCart();const item=cart.items.find(i=>String(i.id)===String(dec.dataset.cartDec));if(item){await updateCartItem(item.id,Number(item.quantity)-1);await refreshCartCount();await renderCart();}return;}
    const remove=e.target.closest('[data-cart-remove]');if(remove){e.preventDefault();await removeCartItem(remove.dataset.cartRemove);await refreshCartCount();await renderCart();return;}
    if(e.target.closest('#checkoutBtn')){e.preventDefault();await openCheckout(openModal,closeModal);return;}
    const button=e.target.closest('[data-add-listing]');if(!button)return;e.preventDefault();const listingId=button.getAttribute('data-add-listing');if(!listingId)return;button.disabled=true;try{const result=await addToCart(listingId,1);if(result.ok){await refreshCartCount();button.dataset.added='true';const old=text('أضف إلى السلة','Ajouter au panier','Add to cart');button.textContent=`✓ ${text('تمت الإضافة','Ajouté','Added')}`;setTimeout(()=>{button.textContent=old;button.dataset.added='false';},1400);window.dispatchEvent(new CustomEvent('soukis:cart-changed'));}else if(result.reason==='auth_required')openAuthModal();else{console.error('Soukis addToCart failed:',result.error||result.reason);openModal(`<p class="msg">${text('تعذر إضافة المنتج إلى السلة.','Impossible d’ajouter le produit au panier.','Could not add the product to the cart.')}</p>`);}}catch(error){console.error('Soukis addToCart exception:',error);openModal(`<p class="msg">${text('حدث خطأ أثناء إضافة المنتج.','Une erreur est survenue.','An error occurred while adding the product.')}</p>`);}finally{button.disabled=false;}
  });
  window.addEventListener('soukis:order-created',refreshCartCount);window.addEventListener('soukis:cart-changed',refreshCartCount);window.addEventListener('soukis:language-changed',()=>{refreshAuthUI();refreshCartCount();});supabase.auth.onAuthStateChange(()=>{refreshAuthUI();refreshCartCount();});refreshAuthUI();refreshCartCount();
}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
