const translations={
 ar:{store:'المتجر',categories:'الفئات',admin:'الإدارة',login:'تسجيل الدخول',logout:'تسجيل الخروج',loggedIn:'مسجل الدخول',signup:'إنشاء حساب',email:'البريد الإلكتروني',password:'كلمة المرور',invalidCredentials:'أدخل بريدًا صحيحًا وكلمة مرور من 6 أحرف على الأقل.',signupSuccess:'تم إنشاء الحساب. تحقق من بريدك الإلكتروني إذا طُلب منك ذلك.',adminLoginRequired:'يجب تسجيل الدخول أولاً.',adminDenied:'ليس لديك صلاحية للوصول إلى لوحة الإدارة.',sell:'+ أضف منتجاً',cart:'🛒',cartLabel:'السلة',languageLabel:'اللغة',close:'إغلاق',heroKicker:'سوق واحد. عالم كامل.',heroTitle:'اكتشف ما تحب، وبِع ما تملك.',heroText:'منصة عصرية للشراء والبيع، مفتوحة للجميع حول العالم.',explore:'استكشف المنتجات',search:'ابحث عن منتج أو فئة...',all:'كل الفئات',latest:'الأحدث',catKicker:'تسوق حسب الفئة',catTitle:'الفئات',productKicker:'منتجات حقيقية',productTitle:'اكتشف الجديد',footer:'Soukis — سوق عالمي بسيط، سريع، ومفتوح للجميع.',notLogged:'غير مسجل',myProducts:'منتجاتي',myOrders:'طلباتي',count:n=>`${n} منتج`,statusActive:'نشط',statusSold:'تم البيع',statusHidden:'مخفي',statusPending:'قيد الانتظار',corporateAds:'إعلانات الشركات'},
 fr:{store:'Boutique',categories:'Catégories',admin:'Administration',login:'Se connecter',logout:'Se déconnecter',loggedIn:'Connecté',signup:'Créer un compte',email:'Adresse e-mail',password:'Mot de passe',invalidCredentials:'Saisissez une adresse e-mail valide et un mot de passe d’au moins 6 caractères.',signupSuccess:'Compte créé. Vérifiez votre e-mail si nécessaire.',adminLoginRequired:'Vous devez d’abord vous connecter.',adminDenied:'Vous n’avez pas accès à l’administration.',sell:'+ Vendre un produit',cart:'🛒',cartLabel:'Panier',languageLabel:'Langue',close:'Fermer',heroKicker:'Un marché. Un monde entier.',heroTitle:'Trouvez ce que vous aimez, vendez ce que vous avez.',heroText:'Une marketplace moderne pour acheter et vendre, ouverte au monde entier.',explore:'Découvrir les produits',search:'Rechercher un produit ou une catégorie...',all:'Toutes les catégories',latest:'Les plus récents',catKicker:'Acheter par catégorie',catTitle:'Catégories',productKicker:'Produits réels',productTitle:'Découvrez les nouveautés',footer:'Soukis — une marketplace mondiale, simple, rapide et ouverte à tous.',notLogged:'Non connecté',myProducts:'Mes produits',myOrders:'Mes commandes',count:n=>`${n} produit${n>1?'s':''}`,statusActive:'Actif',statusSold:'Vendu',statusHidden:'Masqué',statusPending:'En attente',corporateAds:'Publicité d’entreprise'},
 en:{store:'Store',categories:'Categories',admin:'Administration',login:'Sign in',logout:'Sign out',loggedIn:'Signed in',signup:'Create account',email:'Email address',password:'Password',invalidCredentials:'Enter a valid email and a password of at least 6 characters.',signupSuccess:'Account created. Check your email if required.',adminLoginRequired:'You must sign in first.',adminDenied:'You do not have access to the admin panel.',sell:'+ Sell a product',cart:'🛒',cartLabel:'Cart',languageLabel:'Language',close:'Close',heroKicker:'One marketplace. A whole world.',heroTitle:'Discover what you love, sell what you own.',heroText:'A modern marketplace for buying and selling, open to everyone worldwide.',explore:'Explore products',search:'Search for a product or category...',all:'All categories',latest:'Newest',catKicker:'Shop by category',catTitle:'Categories',productKicker:'Real products',productTitle:'Discover what’s new',footer:'Soukis — a simple, fast global marketplace open to everyone.',notLogged:'Not signed in',myProducts:'My products',myOrders:'My orders',count:n=>`${n} product${n===1?'':'s'}`,statusActive:'Active',statusSold:'Sold',statusHidden:'Hidden',statusPending:'Pending',corporateAds:'Corporate advertising'}
};
const flags={ar:'🇩🇿',fr:'🇫🇷',en:'🇬🇧'};const languageNames={ar:'العربية',fr:'Français',en:'English'};
export function getCurrentLanguage(){const saved=localStorage.getItem('soukis-language');return translations[saved]?saved:'ar';}
export function t(key,...args){const value=(translations[getCurrentLanguage()]||translations.ar)[key];return typeof value==='function'?value(...args):(value??key);}
function renderLanguageIcon(lang){const icon=document.getElementById('langIcon');if(!icon)return;const safeLang=translations[lang]?lang:'ar';icon.replaceChildren(document.createTextNode(flags[safeLang]));icon.setAttribute('aria-label',languageNames[safeLang]);icon.setAttribute('title',languageNames[safeLang]);icon.dataset.lang=safeLang;icon.style.fontWeight='900';icon.style.fontFamily='"Apple Color Emoji","Segoe UI Emoji","Noto Color Emoji",sans-serif';}
function applyLanguage(lang){const safeLang=translations[lang]?lang:'ar';const s=translations[safeLang];document.documentElement.lang=safeLang;document.documentElement.dir=safeLang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(key in s)el.textContent=typeof s[key]==='function'?s[key]():s[key];});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const key=el.dataset.i18nPlaceholder;if(key in s)el.placeholder=s[key];});const category=document.querySelector('#category');if(category?.options[0])category.options[0].textContent=s.all;const sort=document.querySelector('#sort');if(sort?.options[0])sort.options[0].textContent=s.latest;const session=document.querySelector('#session');if(session&&!session.dataset.loggedIn)session.textContent=s.notLogged;const select=document.querySelector('#lang');if(select){select.value=safeLang;select.setAttribute('aria-label',s.languageLabel);select.dataset.currentLang=safeLang;Array.from(select.options).forEach(option=>{option.style.fontWeight='700';});select.style.fontWeight='700';}document.querySelector('#cartBtn')?.setAttribute('aria-label',s.cartLabel);document.querySelector('#close')?.setAttribute('aria-label',s.close);renderLanguageIcon(safeLang);localStorage.setItem('soukis-language',safeLang);window.dispatchEvent(new CustomEvent('soukis:language-changed',{detail:{lang:safeLang}}));}
let installedSelect=null;
const onLanguageChange=event=>applyLanguage(event.currentTarget.value);
export function installI18n(){const select=document.querySelector('#lang');if(!select)return;if(installedSelect&&installedSelect!==select){installedSelect.removeEventListener('change',onLanguageChange);installedSelect.removeEventListener('input',onLanguageChange);}select.removeEventListener('change',onLanguageChange);select.removeEventListener('input',onLanguageChange);select.addEventListener('change',onLanguageChange);select.addEventListener('input',onLanguageChange);installedSelect=select;applyLanguage(getCurrentLanguage());window.soukisSetLanguage=applyLanguage;}
