import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SOUKIS_CONFIG } from './app-config.js';
import { getCurrentLanguage } from './i18n.js';

const supabase=createClient(SOUKIS_CONFIG.supabaseUrl,SOUKIS_CONFIG.supabasePublishableKey);let listings=[];
const text=(ar,fr,en)=>getCurrentLanguage()==='ar'?ar:getCurrentLanguage()==='fr'?fr:en;
const locale=()=>getCurrentLanguage()==='ar'?'ar-DZ':getCurrentLanguage()==='fr'?'fr-FR':'en-US';

export function installProductsUI(){const grid=document.querySelector('#grid');if(!grid)return;const search=document.querySelector('#search'),category=document.querySelector('#category'),sort=document.querySelector('#sort'),count=document.querySelector('#count');
const render=()=>{const q=(search?.value||'').trim().toLowerCase();let items=listings.filter(p=>{const value=[p.title,p.name,p.category,p.description,p.location,p.city].filter(Boolean).join(' ').toLowerCase();return(!q||value.includes(q))&&(!category?.value||category.value===p.category)});if(sort?.value==='price-asc')items.sort((a,b)=>Number(a.price||0)-Number(b.price||0));if(sort?.value==='price-desc')items.sort((a,b)=>Number(b.price||0)-Number(a.price||0));if(sort?.value==='oldest')items.sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));else if(!['price-asc','price-desc'].includes(sort?.value))items.sort((a,b)=>new Date(b.created_at||0)-new Date(a.created_at||0));if(count)count.textContent=text(`${items.length} منتج`,`${items.length} produit${items.length>1?'s':''}`,`${items.length} product${items.length===1?'':'s'}`);grid.innerHTML=items.length?items.map(card).join(''):`<div class="empty">${text('لا توجد منتجات مطابقة حاليًا.','Aucun produit correspondant.','No matching products found.')}</div>`;};
search?.addEventListener('input',render);category?.addEventListener('change',render);sort?.addEventListener('change',render);window.addEventListener('soukis:listing-created',()=>load().then(render));window.addEventListener('soukis:listings-changed',()=>load().then(render));window.addEventListener('soukis:language-changed',()=>{fillFilters(true);render();});load().then(render);
async function load(){grid.innerHTML=`<div class="empty">${text('جاري تحميل المنتجات…','Chargement des produits…','Loading products…')}</div>`;const{data,error}=await supabase.from('listings').select('*').order('created_at',{ascending:false});if(error){grid.innerHTML=`<div class="empty">${text('تعذر تحميل المنتجات. تحقق من إعدادات Supabase.','Impossible de charger les produits. Vérifiez Supabase.','Could not load products. Check Supabase settings.')}</div>`;return;}listings=data||[];fillFilters(false);}
function fillFilters(preserve){const oldCategory=category?.value||'',oldSort=sort?.value||'';const categories=[...new Set(listings.map(p=>p.category).filter(Boolean))].sort();if(category)category.innerHTML=`<option value="">${text('كل الفئات','Toutes les catégories','All categories')}</option>`+categories.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');if(sort)sort.innerHTML=`<option value="">${text('الأحدث','Les plus récents','Newest')}</option><option value="price-asc">${text('السعر: من الأقل','Prix : croissant','Price: low to high')}</option><option value="price-desc">${text('السعر: من الأعلى','Prix : décroissant','Price: high to low')}</option><option value="oldest">${text('الأقدم','Les plus anciens','Oldest')}</option>`;if(preserve){if(category&&categories.includes(oldCategory))category.value=oldCategory;if(sort&&['','price-asc','price-desc','oldest'].includes(oldSort))sort.value=oldSort;}const cats=document.querySelector('#cats');if(cats)cats.innerHTML=categories.slice(0,12).map(c=>`<button class="cat" data-cat="${esc(c)}"><i>▦</i>${esc(c)}</button>`).join('');cats?.querySelectorAll('[data-cat]').forEach(b=>b.addEventListener('click',()=>{if(category){category.value=b.dataset.cat;category.dispatchEvent(new Event('change'));document.querySelector('#products')?.scrollIntoView({behavior:'smooth'});}}));}
}
function card(p){const id=esc(p.id),title=esc(p.title||p.name||text('منتج','Produit','Product')),category=esc(p.category||text('عام','Général','General')),location=esc(p.location||p.city||''),price=Number(p.price||0).toLocaleString(locale()),currency=esc(p.currency||'DA'),image=p.image_url||p.image||'';return `<article class="product"><div class="pic">${image?`<img src="${esc(image)}" alt="${title}" loading="lazy">`:'<span class="emoji">🛍️</span>'}</div><div class="body"><small>${category}</small><h3>${title}</h3><div class="price">${price} ${currency}</div><div class="loc">${location}</div><button class="cart" data-add-listing="${id}" data-listing-id="${id}">🛒 ${text('أضف إلى السلة','Ajouter au panier','Add to cart')}</button></div></article>`;}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
