import { db } from './supabase.js';
import { getCurrentLanguage } from './i18n.js';

const text=(ar,fr,en)=>getCurrentLanguage()==='ar'?ar:getCurrentLanguage()==='fr'?fr:en;

export async function openSellModal(openModal,closeModal,onCreated=()=>{}){
  const {data:{user}}=await db.auth.getUser();
  if(!user){openModal(`<h2>${text('تسجيل الدخول مطلوب','Connexion requise','Sign in required')}</h2><p class="msg">${text('سجّل الدخول أولًا حتى تتمكن من نشر منتج.','Connectez-vous pour publier un produit.','Sign in first to publish a product.')}</p><button class="blue" id="sellLogin" type="button">${text('تسجيل الدخول','Se connecter','Sign in')}</button>`);document.querySelector('#sellLogin')?.addEventListener('click',()=>document.querySelector('#authBtn')?.click());return;}
  const {data:categories,error:catError}=await db.from('categories').select('id,name_ar,name_fr,name_en').order('name_en');
  const {data:cities,error:cityError}=await db.from('cities').select('id,name_ar,name_fr,name_en').order('name_en');
  if(catError||cityError){openModal(`<h2>${text('تعذر تحميل البيانات','Impossible de charger les données','Could not load form data')}</h2><p class="msg">${catError?.message||cityError?.message||''}</p>`);return;}
  const lang=getCurrentLanguage();
  const label=(row)=>lang==='ar'?row.name_ar:lang==='fr'?row.name_fr:row.name_en;
  openModal(`<h2>${text('أضف منتجًا','Ajouter un produit','Add a product')}</h2><p class="msg">${text('انشر منتجك ليظهر في سوق Soukis.','Publiez votre produit sur Soukis.','Publish your product on Soukis.')}</p><form id="sellForm" class="form"><input name="title" required maxlength="120" placeholder="${text('اسم المنتج','Nom du produit','Product name')}"><input name="price" required type="number" min="0" step="0.01" placeholder="${text('السعر','Prix','Price')}"><select name="category_id" required><option value="">${text('اختر الفئة','Choisir une catégorie','Choose a category')}</option>${categories.map(c=>`<option value="${c.id}">${label(c)}</option>`).join('')}</select><select name="city_id"><option value="">${text('اختر المدينة','Choisir la ville','Choose a city')}</option>${cities.map(c=>`<option value="${c.id}">${label(c)}</option>`).join('')}</select><input name="seller_name" maxlength="120" placeholder="${text('اسم البائع','Nom du vendeur','Seller name')}"><input name="seller_phone" maxlength="40" placeholder="${text('رقم الهاتف (اختياري)','Téléphone (facultatif)','Phone (optional)')}"><label>${text('صورة المنتج','Photo du produit','Product photo')}<input name="image" type="file" accept="image/jpeg,image/png,image/webp,image/gif"></label><textarea name="description" maxlength="2000" placeholder="${text('وصف المنتج','Description du produit','Product description')}"></textarea><button class="blue" type="submit">${text('نشر المنتج','Publier le produit','Publish product')}</button><p id="sellMessage" class="msg" hidden></p></form>`);
  const form=document.querySelector('#sellForm'),message=document.querySelector('#sellMessage');
  form?.addEventListener('submit',async event=>{event.preventDefault();const submit=form.querySelector('button[type="submit"]');submit.disabled=true;message.hidden=false;message.textContent=text('جارٍ نشر المنتج…','Publication du produit…','Publishing product…');let uploadedPath=null;try{const values=Object.fromEntries(new FormData(form));const title=String(values.title||'').trim();const price=Number(values.price);if(!title)throw new Error(text('أدخل اسم المنتج.','Saisissez le nom du produit.','Enter a product name.'));if(!Number.isFinite(price)||price<0)throw new Error(text('أدخل سعرًا صالحًا.','Saisissez un prix valide.','Enter a valid price.'));let image_url=null;const file=form.querySelector('input[name="image"]')?.files?.[0];if(file){const allowed=['image/jpeg','image/png','image/webp','image/gif'];if(!allowed.includes(file.type))throw new Error(text('صيغة الصورة غير مدعومة. استخدم JPG أو PNG أو WebP أو GIF.','Format d’image non pris en charge. Utilisez JPG, PNG, WebP ou GIF.','Unsupported image type. Use JPG, PNG, WebP, or GIF.'));if(file.size>5*1024*1024)throw new Error(text('حجم الصورة يجب ألا يتجاوز 5MB.','L’image ne doit pas dépasser 5 Mo.','Image must be 5MB or smaller.'));const ext=file.type==='image/jpeg'?'jpg':file.type.split('/')[1];uploadedPath=`${user.id}/${crypto.randomUUID()}.${ext}`;const {error:uploadError}=await db.storage.from('product-images').upload(uploadedPath,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const {data:urlData}=db.storage.from('product-images').getPublicUrl(uploadedPath);image_url=urlData.publicUrl;}const payload={user_id:user.id,title,price,category_id:values.category_id,city_id:values.city_id||null,seller_name:String(values.seller_name||'').trim()||null,seller_phone:String(values.seller_phone||'').trim()||null,image_url,description:String(values.description||'').trim()||null};const {error}=await db.from('listings').insert(payload);if(error)throw error;message.textContent=text('تم نشر المنتج بنجاح ✓','Produit publié avec succès ✓','Product published successfully ✓');window.dispatchEvent(new CustomEvent('soukis:listing-created'));onCreated();setTimeout(closeModal,700);}catch(error){if(uploadedPath){await db.storage.from('product-images').remove([uploadedPath]);}message.textContent=`${text('تعذر نشر المنتج:','Impossible de publier le produit :','Could not publish the product:')} ${error?.message||text('خطأ غير معروف.','Erreur inconnue.','Unknown error.')}`;}finally{submit.disabled=false;}});
}
