import { db } from './supabase.js';
import { getCurrentLanguage } from './i18n.js';

const text=(ar,fr,en)=>getCurrentLanguage()==='ar'?ar:getCurrentLanguage()==='fr'?fr:en;

export async function openSellModal(openModal,closeModal,onCreated=()=>{}){
  const {data:{user}}=await db.auth.getUser();
  if(!user){openModal(`<h2>${text('تسجيل الدخول مطلوب','Connexion requise','Sign in required')}</h2><p class="msg">${text('سجّل الدخول أولًا حتى تتمكن من نشر منتج.','Connectez-vous pour publier un produit.','Sign in first to publish a product.')}</p><button class="blue" id="sellLogin">${text('تسجيل الدخول','Se connecter','Sign in')}</button>`);document.querySelector('#sellLogin')?.addEventListener('click',()=>document.querySelector('#authBtn')?.click());return;}
  openModal(`<h2>${text('أضف منتجًا','Ajouter un produit','Add a product')}</h2><p class="msg">${text('انشر منتجك ليظهر في سوق Soukis.','Publiez votre produit sur Soukis.','Publish your product on Soukis.')}</p><form id="sellForm" class="form"><input name="title" required maxlength="120" placeholder="${text('اسم المنتج','Nom du produit','Product name')}"><input name="price" required type="number" min="0" step="0.01" placeholder="${text('السعر','Prix','Price')}"><input name="category" required maxlength="60" placeholder="${text('الفئة','Catégorie','Category')}"><input name="location" maxlength="120" placeholder="${text('الموقع / المدينة','Lieu / ville','Location / city')}"><input name="seller_name" maxlength="120" placeholder="${text('اسم البائع','Nom du vendeur','Seller name')}"><input name="seller_phone" maxlength="40" placeholder="${text('رقم الهاتف (اختياري)','Téléphone (facultatif)','Phone (optional)')}"><input name="image_url" type="url" maxlength="1000" placeholder="${text('رابط صورة المنتج (اختياري)','URL de l’image (facultatif)','Product image URL (optional)')}"><textarea name="description" maxlength="2000" placeholder="${text('وصف المنتج','Description du produit','Product description')}"></textarea><button class="blue" type="submit">${text('نشر المنتج','Publier le produit','Publish product')}</button><p id="sellMessage" class="msg" hidden></p></form>`);
  const form=document.querySelector('#sellForm'),message=document.querySelector('#sellMessage');
  form?.addEventListener('submit',async event=>{event.preventDefault();const submit=form.querySelector('button[type="submit"]');submit.disabled=true;message.hidden=false;message.textContent=text('جارٍ نشر المنتج…','Publication du produit…','Publishing product…');const values=Object.fromEntries(new FormData(form));const payload={user_id:user.id,title:values.title.trim(),price:Number(values.price),category:values.category.trim(),location:values.location.trim()||null,seller_name:values.seller_name.trim()||null,seller_phone:values.seller_phone.trim()||null,image_url:values.image_url.trim()||null,description:values.description.trim()||null};const {error}=await db.from('listings').insert(payload);submit.disabled=false;if(error){message.textContent=`${text('تعذر نشر المنتج:','Impossible de publier le produit :','Could not publish the product:')} ${error.message}`;return;}message.textContent=text('تم نشر المنتج بنجاح ✓','Produit publié avec succès ✓','Product published successfully ✓');window.dispatchEvent(new CustomEvent('soukis:listing-created'));onCreated();setTimeout(closeModal,700);});
}
